#!/bin/bash

if [ "$(git status -s)" != "" ]; then
  echo "Unstaged changes, commit everything before pushing"
  echo
  exit 1
fi

clojure -M:test

if [ "$?" != "0" ]; then
  exit 1
fi

clojure -M:test/cljs

